FROM node:19

WORKDIR /usr/src/app

RUN npm config set proxy http://wwwproxy.uni-muenster.de:3128

COPY package*.json ./

RUN npm install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

EXPOSE 8080
