FROM node:19 as build-stage

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage usr/src/app/data/nginx/nginx.conf /etc/nginx/conf.d/default.conf:ro
COPY --from=build-stage usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

