version: '3.8'
services:
  app:
    image: backend_prod:latest
    build:
      context: backend
      dockerfile: Dockerfile.vm.prod
    volumes:
      - ./backend/:/app
    ports:
      - 9999:9999
    command: bash -c 'printenv >> /etc/environment && service cron start && python manage.py runserver 0.0.0.0:9999'
    env_file:
      - database-variables.env
      - prod-variables.env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - database-variables.env
    expose:
      - '5433'
    ports:
      - '5433:5432'
    command: -p 5433
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    env_file:
      - database-variables.env
    ports:
      - '8888:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
  celery:
    build:
      context: backend
      dockerfile: Dockerfile.vm.prod
    command: celery -A mensa_recommend worker -l INFO
    volumes:
      - ./backend/:/app
    env_file:
      - database-variables.env
      - prod-variables.env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
  redis:
    image: 'redis:alpine'
  frontend:
    image: frontend_prod:latest
    build:
      context: frontend
      dockerfile: Dockerfile.vm.prod
    ports:
      - '80:80'
    container_name: vue-ui
    env_file:
      - prod-variables.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
      - ./frontend/data/nginx:/etc/nginx/conf.d
      - ./frontend/data/certbot/conf:/etc/letsencrypt
      - ./frontend/data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./frontend/data/certbot/conf:/etc/letsencrypt
      - ./frontend/data/certbot/www:/var/www/certbot

volumes:
  postgres_data:
  pgadmin_data:
