# Generated by Django 4.1.3 on 2022-11-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
