# Generated by Django 4.1.3 on 2022-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0002_additive_dishplan_alter_allergy_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='las_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(through='mensa.UserAllergy', to='mensa.allergy'),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(through='mensa.UserCategory', to='mensa.category'),
        ),
    ]
