# Generated by Django 4.1.3 on 2022-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_las_name_user_last_name_user_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
