# Generated by Django 4.1.3 on 2023-01-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensa', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('weekDay', 'startTime', 'endTime', 'rythm', 'startDate', 'endDate'), name='unique timeslot'),
        ),
        migrations.AddField(
            model_name='roommensadistance',
            name='mensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='roommensadistance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='mensen',
            field=models.ManyToManyField(through='courses.RoomMensaDistance', to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.timeslot'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(through='courses.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('course', 'timeslot', 'room'), name='unique reservation'),
        ),
    ]
