# Generated by Django 4.1.3 on 2022-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('course', 'timeslot', 'room'), name='unique reservation'),
        ),
    ]
