version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 9999:9999
    command: python manage.py runserver 0.0.0.0:9999
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: