version: '3.8'
services:
  app:
    build: .
    image: mensa_app
    volumes:
      - .:/app
    ports:
      - 9999:9999
    command: python manage.py runserver 0.0.0.0:9999
    env_file:
      - database-variables.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - database-variables.env
    expose:
      - '5433'
    ports:
      - '5433:5432'
    command: -p 5433
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    env_file:
      - database-variables.env
    ports:
      - '8888:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
