# Generated by Django 4.1.3 on 2023-01-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersideselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='userdishrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.category'),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.allergy'),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensa',
            name='dishes',
            field=models.ManyToManyField(through='mensa.DishPlan', to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='mensa',
            name='ext_ratings',
            field=models.ManyToManyField(related_name='mensa_ext_ratings', through='mensa.ExtDishRating', to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='mensa',
            name='rooms',
            field=models.ManyToManyField(through='courses.RoomMensaDistance', to='courses.room'),
        ),
        migrations.AddField(
            model_name='extdishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='extdishrating',
            name='mensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='dishplan',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='dishplan',
            name='mensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='dishplan',
            name='user',
            field=models.ManyToManyField(through='mensa.UserSideSelection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.category'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='dishallergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.allergy'),
        ),
        migrations.AddField(
            model_name='dishallergy',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='dishadditive',
            name='additive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.additive'),
        ),
        migrations.AddField(
            model_name='dishadditive',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='additives',
            field=models.ManyToManyField(through='mensa.DishAdditive', to='mensa.additive'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergies',
            field=models.ManyToManyField(through='mensa.DishAllergy', to='mensa.allergy'),
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(through='mensa.DishCategory', to='mensa.category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ext_ratings',
            field=models.ManyToManyField(related_name='dish_ext_ratings', through='mensa.ExtDishRating', to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='dish',
            name='mensen',
            field=models.ManyToManyField(through='mensa.DishPlan', to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='dish',
            name='users',
            field=models.ManyToManyField(through='mensa.UserDishRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='dishes',
            field=models.ManyToManyField(through='mensa.DishCategory', to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(through='mensa.UserCategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergy',
            name='allergies',
            field=models.ManyToManyField(through='mensa.DishAllergy', to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='users',
            field=models.ManyToManyField(through='mensa.UserAllergy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additive',
            name='additives',
            field=models.ManyToManyField(through='mensa.DishAdditive', to='mensa.dish'),
        ),
        migrations.AlterUniqueTogether(
            name='extdishrating',
            unique_together={('dish', 'mensa', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dishplan',
            unique_together={('dish', 'mensa', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dishcategory',
            unique_together={('dish', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='dishallergy',
            unique_together={('dish', 'allergy')},
        ),
        migrations.AlterUniqueTogether(
            name='dishadditive',
            unique_together={('dish', 'additive')},
        ),
        migrations.AlterUniqueTogether(
            name='cardbalance',
            unique_together={('id', 'date')},
        ),
    ]
