# Generated by Django 4.1.3 on 2022-12-27 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensa', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSideSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='mensa.dishplan')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side', to='mensa.dishplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dishplan',
            name='user',
            field=models.ManyToManyField(through='mensa.UserSideSelection', to=settings.AUTH_USER_MODEL),
        ),
    ]
