# Generated by Django 4.1.3 on 2023-01-12 22:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensa', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersideselection',
            unique_together={('main', 'user', 'side')},
        ),
    ]
