# Generated by Django 4.1.3 on 2023-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0004_alter_userdishrating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='translation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
