# Generated by Django 4.1.3 on 2022-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('publishId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('learnweb_abbr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=80)),
                ('seats', models.IntegerField(null=True)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMensaDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('rythm', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('weekDay', 'startTime', 'endTime', 'rythm', 'startDate', 'endDate'), name='unique timeslot'),
        ),
    ]
