# Generated by Django 4.1.3 on 2022-11-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique appversion',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('weekDay', 'startTime', 'endTime', 'rythm'), name='unique timeslot'),
        ),
    ]
