# Generated by Django 4.1.3 on 2022-11-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('mensa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommensadistance',
            name='mensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='roommensadistance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='mensen',
            field=models.ManyToManyField(through='courses.RoomMensaDistance', to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.timeslot'),
        ),
    ]
