# Generated by Django 4.1.3 on 2022-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_room_course_users_timeslot_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
