# Generated by Django 4.1.3 on 2022-11-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learnweb_abbr',
            field=models.CharField(max_length=50),
        ),
    ]
