# Generated by Django 4.1.3 on 2022-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_learnweb_abbr'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique timeslot',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('weekDay', 'startTime', 'endTime', 'rythm', 'startDate', 'endDate'), name='unique timeslot'),
        ),
    ]
