# Generated by Django 4.1.3 on 2022-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_timeslot_unique timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=13, null=True),
        ),
    ]
