# Generated by Django 4.1.3 on 2022-11-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0005_additive_dishadditive_additive_additives'),
        ('courses', '0008_room_lat_room_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMensaDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('mensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='mensen',
            field=models.ManyToManyField(through='courses.RoomMensaDistance', to='mensa.mensa'),
        ),
    ]
