name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
    - "**"

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./backend/Dockerfile.prod
            context: ./backend/
            image: mensatoday/mensatoday
          - dockerfile: ./frontend/Dockerfile.prod
            context: ./frontend/
            image: mensatoday/mensatoday
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ matrix.image }}

    - name: Build the Docker image
      uses: docker/build-push-action@v4.0.0
      with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
