# Generated by Django 4.1.3 on 2022-11-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.category')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.allergy')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='allergies',
            field=models.ManyToManyField(through='mensa.DishAllergy', to='mensa.allergy'),
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(through='mensa.DishCategory', to='mensa.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='dishes',
            field=models.ManyToManyField(through='mensa.DishCategory', to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='allergies',
            field=models.ManyToManyField(through='mensa.DishAllergy', to='mensa.dish'),
        ),
    ]
