# Generated by Django 4.1.3 on 2022-11-22 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Additive',
                'verbose_name_plural': 'Additives',
            },
        ),
        migrations.CreateModel(
            name='DishPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('priceStudent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('priceEmployee', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Allergy', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=100)),
                ('housenumer', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('dishes', models.ManyToManyField(through='mensa.DishPlan', to='mensa.dish')),
            ],
            options={
                'verbose_name': 'Mensa',
                'verbose_name_plural': 'Mensen',
            },
        ),
        migrations.AddField(
            model_name='dishplan',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='dishplan',
            name='mensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa'),
        ),
        migrations.CreateModel(
            name='DishAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.additive')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish')),
            ],
        ),
        migrations.AddField(
            model_name='additive',
            name='additives',
            field=models.ManyToManyField(through='mensa.DishAdditive', to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='users',
            field=models.ManyToManyField(through='mensa.UserAllergy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(through='mensa.UserCategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='mensen',
            field=models.ManyToManyField(through='mensa.DishPlan', to='mensa.mensa'),
        ),
        migrations.CreateModel(
            name='CardBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'date')},
            },
        ),
    ]
