# Generated by Django 4.1.3 on 2022-11-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0002_additive_dishplan_alter_allergy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbalance',
            name='card_id',
        ),
    ]
