# Generated by Django 4.1.3 on 2022-11-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0002_usercategory_userallergy_allergy_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=100)),
                ('housenumer', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
            options={
                'verbose_name': 'Mensa',
                'verbose_name_plural': 'Mensen',
            },
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Allergy', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
    ]
