# Generated by Django 4.1.3 on 2022-11-12 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensa', '0003_mensa_alter_allergy_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('priceStudent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('priceEmployee', models.DecimalField(decimal_places=2, max_digits=2)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish')),
                ('mensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa')),
            ],
        ),
        migrations.CreateModel(
            name='CardBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='mensen',
            field=models.ManyToManyField(through='mensa.DishPlan', to='mensa.mensa'),
        ),
        migrations.AddField(
            model_name='mensa',
            name='dishes',
            field=models.ManyToManyField(through='mensa.DishPlan', to='mensa.dish'),
        ),
    ]
