# Generated by Django 4.1.3 on 2022-11-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0004_dishplan_cardbalance_dish_mensen_mensa_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Additive',
                'verbose_name_plural': 'Additives',
            },
        ),
        migrations.CreateModel(
            name='DishAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.additive')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish')),
            ],
        ),
        migrations.AddField(
            model_name='additive',
            name='additives',
            field=models.ManyToManyField(through='mensa.DishAdditive', to='mensa.dish'),
        ),
    ]
