# Generated by Django 4.1.3 on 2022-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_roommensadistance_room_mensen'),
        ('mensa', '0005_additive_dishadditive_additive_additives'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensa',
            name='rooms',
            field=models.ManyToManyField(through='courses.RoomMensaDistance', to='courses.room'),
        ),
    ]
